language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"

notifications:
  email:
    - mwhooker@disqus.com
    - ted@disqus.com
  irc: "irc.freenode.org#samsa"

before_install:
    - sudo apt-get install -qq zookeeper libev-dev
    - make -C vendor kafka > /dev/null
    - sudo mv vendor/kafka /usr/local/kafka

env:
    global:
        - ZOOKEEPER_PATH=/usr/share/java
        - KAFKA_PATH=/usr/local/kafka
        - KAFKA_START_TIMEOUT=30
    matrix:
        - KAZOO_VERSION='>=0.5,<0.6'
        - KAZOO_VERSION='>=0.6,<0.7'

install:
    - pip install --use-mirrors kazoo$KAZOO_VERSION

script: make test
